name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.12
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.12

    - name: Install dependencies
      run: make install

    - name: Lint
      run: make lint

    - name: Format
      run: make format
      
    - name: Test
      run: make test
